site_name: LazySlide

nav:
- Home: index.md
- Development: development.md
- API:
    - api/WSI.md
    - api/reader.md

theme:
  name: 'material'
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            docstring_style: numpy
            header_level: 2
            show_source: false
            show_object_full_path: false
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            unwrap_annotated: true
            signature_crossrefs: true

            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

#  - mkdocs-material-extensions
#  - mkdocs-awesome-pages-plugin
#  - mkdocs-minify-plugin
#  - mkdocs-macros-plugin
#  - mkdocs-git-revision-date-localized-plugin
#  - mkdocs-git-authors-plugin
#  - mkdocs-git-authors-plugin
#  - mkdocs