name: Publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/docker_image.yaml'
      - 'src/**'
      - 'pyproject.toml'

  pull_request:
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/docker_image.yaml'
      - 'src/**'
      - 'pyproject.toml'
  
  release:
    types: [published]

jobs:
  Build_and_Push_Docker_Image:
    runs-on: linux-docker-build # Use a paid runner with 150G disk space
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (version)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/lazyslide
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Generate artifact attestation
        if: github.event_name == 'release'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/lazyslide
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Verify Docker image
        if: github.event_name == 'release'
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/lazyslide:${{ steps.meta.outputs.tags }} lazyslide --version

